name: Run Cypress E2E Tests
on:
  push:
    branches:
      - M3-daily-update
jobs:
  run-cypress-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://github.community/t/secrets-in-matrix/17307/3
        user: [personal-account, prod-test-001, prod-test-002, prod-test-008]
        include:
          - user: personal-account
            manager_oauth: MANAGER_OAUTH_1
          - user: prod-test-001
            manager_oauth: MANAGER_OAUTH_2
          - user: prod-test-002
            manager_oauth: MANAGER_OAUTH_3
          - user: prod-test-008
            manager_oauth: MANAGER_OAUTH_4

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - run: |
          echo "MANAGER_OAUTH=${{ secrets[matrix.manager_oauth] }}" >> ./packages/manager/.env
      - run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REACT_APP_LAUNCH_DARKLY_ID=${{ secrets.REACT_APP_LAUNCH_DARKLY_ID }}" >> ./packages/manager/.env
          echo "REACT_APP_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> ./packages/manager/.env
          yarn up &
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/manager
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 1000
          install: false
          browser: chrome
          headless: true
          record: true
          parallel: true
